# Generated by Django 5.1.7 on 2025-03-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0002_about_portfolio_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='picture'),
        ),
    ]
