# Generated by Django 5.2.7 on 2025-10-22 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0003_profile_last_login_ip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
