# Generated by Django 5.1.7 on 2025-04-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0004_contact_signupform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='contact',
            name='lname',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
