# Generated by Django 5.1.7 on 2025-04-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0006_contact_company_name_alter_contact_fname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
