# Generated by Django 5.1.7 on 2025-04-09 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0007_contact_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='username',
        ),
    ]
