# Generated by Django 5.1.7 on 2025-04-11 15:09

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0008_remove_contact_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=15, region=None, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+234 803 099 9999'. Up to 15 digits is allowed.", regex='^\\+?1?\\d{9, 15}$')]),
        ),
    ]
