# Generated by Django 5.1.7 on 2025-04-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mars', '0009_portfoliovideo_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliovideo',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='video'),
        ),
    ]
