# Generated by Django 5.2.7 on 2025-10-24 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_rename_profile_image_userprofile_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password2',
        ),
    ]
